<template>
  <div class="wrapper">
    <ul class="content">
      <li>分类列表1</li>
      <li>分类列表2</li>
      <li>分类列表3</li>
      <li>分类列表4</li>
      <li>分类列表5</li>
      <li>分类列表6</li>
      <li>分类列表7</li>
      <li>分类列表8</li>
      <li>分类列表9</li>
      <li>分类列表10</li>
      <li>分类列表11</li>
      <li>分类列表12</li>
      <li>分类列表13</li>
      <li>分类列表14</li>
      <li>分类列表15</li>
      <li>分类列表16</li>
      <li>分类列表17</li>
      <li>分类列表18</li>
      <li>分类列表19</li>
      <li>分类列表20</li>
      <li>分类列表21</li>
      <li>分类列表22</li>
      <li>分类列表23</li>
      <li>分类列表24</li>
      <li>分类列表25</li>
      <li>分类列表26</li>
      <li>分类列表27</li>
      <li>分类列表28</li>
      <li>分类列表29</li>
      <li>分类列表30</li>
      <li>分类列表31</li>
      <li>分类列表32</li>
      <li>分类列表33</li>
      <li>分类列表34</li>
      <li>分类列表35</li>
      <li>分类列表36</li>
      <li>分类列表37</li>
      <li>分类列表38</li>
      <li>分类列表39</li>
      <li>分类列表40</li>
      <li>分类列表41</li>
      <li>分类列表42</li>
      <li>分类列表43</li>
      <li>分类列表44</li>
      <li>分类列表45</li>
      <li>分类列表46</li>
      <li>分类列表47</li>
      <li>分类列表48</li>
      <li>分类列表49</li>
      <li>分类列表50</li>
      <li>分类列表51</li>
      <li>分类列表52</li>
      <li>分类列表53</li>
      <li>分类列表54</li>
      <li>分类列表55</li>
      <li>分类列表56</li>
      <li>分类列表57</li>
      <li>分类列表58</li>
      <li>分类列表59</li>
      <li>分类列表60</li>
      <li>分类列表61</li>
      <li>分类列表62</li>
      <li>分类列表63</li>
      <li>分类列表64</li>
      <li>分类列表65</li>
      <li>分类列表66</li>
      <li>分类列表67</li>
      <li>分类列表68</li>
      <li>分类列表69</li>
      <li>分类列表70</li>
      <li>分类列表71</li>
      <li>分类列表72</li>
      <li>分类列表73</li>
      <li>分类列表74</li>
      <li>分类列表75</li>
      <li>分类列表76</li>
      <li>分类列表77</li>
      <li>分类列表78</li>
      <li>分类列表79</li>
      <li>分类列表80</li>
      <li>分类列表81</li>
      <li>分类列表82</li>
      <li>分类列表83</li>
      <li>分类列表84</li>
      <li>分类列表85</li>
      <li>分类列表86</li>
      <li>分类列表87</li>
      <li>分类列表88</li>
      <li>分类列表89</li>
      <li>分类列表90</li>
      <li>分类列表91</li>
      <li>分类列表92</li>
      <li>分类列表93</li>
      <li>分类列表94</li>
      <li>分类列表95</li>
      <li>分类列表96</li>
      <li>分类列表97</li>
      <li>分类列表98</li>
      <li>分类列表99</li>
      <li>分类列表100</li>
      <li>分类列表A-1</li>
      <li>分类列表A-2</li>
      <li>分类列表A-3</li>
      <li>分类列表A-4</li>
      <li>分类列表A-5</li>
      <li>分类列表A-6</li>
      <li>分类列表A-7</li>
      <li>分类列表A-8</li>
      <li>分类列表A-9</li>
      <li>分类列表A-10</li>
      <li>分类列表A-11</li>
      <li>分类列表A-12</li>
      <li>分类列表A-13</li>
      <li>分类列表A-14</li>
      <li>分类列表A-15</li>
      <li>分类列表A-16</li>
      <li>分类列表A-17</li>
      <li>分类列表A-18</li>
      <li>分类列表A-19</li>
      <li>分类列表A-20</li>
      <li>分类列表A-21</li>
      <li>分类列表A-22</li>
      <li>分类列表A-23</li>
      <li>分类列表A-24</li>
      <li>分类列表A-25</li>
      <li>分类列表A-26</li>
      <li>分类列表A-27</li>
      <li>分类列表A-28</li>
      <li>分类列表A-29</li>
      <li>分类列表A-30</li>
      <li>分类列表A-31</li>
      <li>分类列表A-32</li>
      <li>分类列表A-33</li>
      <li>分类列表A-34</li>
      <li>分类列表A-35</li>
      <li>分类列表A-36</li>
      <li>分类列表A-37</li>
      <li>分类列表A-38</li>
      <li>分类列表A-39</li>
      <li>分类列表A-40</li>
      <li>分类列表A-41</li>
      <li>分类列表A-42</li>
      <li>分类列表A-43</li>
      <li>分类列表A-44</li>
      <li>分类列表A-45</li>
      <li>分类列表A-46</li>
      <li>分类列表A-47</li>
      <li>分类列表A-48</li>
      <li>分类列表A-49</li>
      <li>分类列表A-50</li>
      <li>分类列表A-51</li>
      <li>分类列表A-52</li>
      <li>分类列表A-53</li>
      <li>分类列表A-54</li>
      <li>分类列表A-55</li>
      <li>分类列表A-56</li>
      <li>分类列表A-57</li>
      <li>分类列表A-58</li>
      <li>分类列表A-59</li>
      <li>分类列表A-60</li>
      <li>分类列表A-61</li>
      <li>分类列表A-62</li>
      <li>分类列表A-63</li>
      <li>分类列表A-64</li>
      <li>分类列表A-65</li>
      <li>分类列表A-66</li>
      <li>分类列表A-67</li>
      <li>分类列表A-68</li>
      <li>分类列表A-69</li>
      <li>分类列表A-70</li>
      <li>分类列表A-71</li>
      <li>分类列表A-72</li>
      <li>分类列表A-73</li>
      <li>分类列表A-74</li>
      <li>分类列表A-75</li>
      <li>分类列表A-76</li>
      <li>分类列表A-77</li>
      <li>分类列表A-78</li>
      <li>分类列表A-79</li>
      <li>分类列表A-80</li>
      <li>分类列表A-81</li>
      <li>分类列表A-82</li>
      <li>分类列表A-83</li>
      <li>分类列表A-84</li>
      <li>分类列表A-85</li>
      <li>分类列表A-86</li>
      <li>分类列表A-87</li>
      <li>分类列表A-88</li>
      <li>分类列表A-89</li>
      <li>分类列表A-90</li>
      <li>分类列表A-91</li>
      <li>分类列表A-92</li>
      <li>分类列表A-93</li>
      <li>分类列表A-94</li>
      <li>分类列表A-95</li>
      <li>分类列表A-96</li>
      <li>分类列表A-97</li>
      <li>分类列表A-98</li>
      <li>分类列表A-99</li>
      <li>分类列表A-100</li>
      <li>分类列表S-1</li>
      <li>分类列表S-2</li>
      <li>分类列表S-3</li>
      <li>分类列表S-4</li>
      <li>分类列表S-5</li>
      <li>分类列表S-6</li>
      <li>分类列表S-7</li>
      <li>分类列表S-8</li>
      <li>分类列表S-9</li>
      <li>分类列表S-10</li>
      <li>分类列表S-11</li>
      <li>分类列表S-12</li>
      <li>分类列表S-13</li>
      <li>分类列表S-14</li>
      <li>分类列表S-15</li>
      <li>分类列表S-16</li>
      <li>分类列表S-17</li>
      <li>分类列表S-18</li>
      <li>分类列表S-19</li>
      <li>分类列表S-20</li>
      <li>分类列表S-21</li>
      <li>分类列表S-22</li>
      <li>分类列表S-23</li>
      <li>分类列表S-24</li>
      <li>分类列表S-25</li>
      <li>分类列表S-26</li>
      <li>分类列表S-27</li>
      <li>分类列表S-28</li>
      <li>分类列表S-29</li>
      <li>分类列表S-30</li>
      <li>分类列表S-31</li>
      <li>分类列表S-32</li>
      <li>分类列表S-33</li>
      <li>分类列表S-34</li>
      <li>分类列表S-35</li>
      <li>分类列表S-36</li>
      <li>分类列表S-37</li>
      <li>分类列表S-38</li>
      <li>分类列表S-39</li>
      <li>分类列表S-40</li>
      <li>分类列表S-41</li>
      <li>分类列表S-42</li>
      <li>分类列表S-43</li>
      <li>分类列表S-44</li>
      <li>分类列表S-45</li>
      <li>分类列表S-46</li>
      <li>分类列表S-47</li>
      <li>分类列表S-48</li>
      <li>分类列表S-49</li>
      <li>分类列表S-50</li>
      <li>分类列表S-51</li>
      <li>分类列表S-52</li>
      <li>分类列表S-53</li>
      <li>分类列表S-54</li>
      <li>分类列表S-55</li>
      <li>分类列表S-56</li>
      <li>分类列表S-57</li>
      <li>分类列表S-58</li>
      <li>分类列表S-59</li>
      <li>分类列表S-60</li>
      <li>分类列表S-61</li>
      <li>分类列表S-62</li>
      <li>分类列表S-63</li>
      <li>分类列表S-64</li>
      <li>分类列表S-65</li>
      <li>分类列表S-66</li>
      <li>分类列表S-67</li>
      <li>分类列表S-68</li>
      <li>分类列表S-69</li>
      <li>分类列表S-70</li>
      <li>分类列表S-71</li>
      <li>分类列表S-72</li>
      <li>分类列表S-73</li>
      <li>分类列表S-74</li>
      <li>分类列表S-75</li>
      <li>分类列表S-76</li>
      <li>分类列表S-77</li>
      <li>分类列表S-78</li>
      <li>分类列表S-79</li>
      <li>分类列表S-80</li>
      <li>分类列表S-81</li>
      <li>分类列表S-82</li>
      <li>分类列表S-83</li>
      <li>分类列表S-84</li>
      <li>分类列表S-85</li>
      <li>分类列表S-86</li>
      <li>分类列表S-87</li>
      <li>分类列表S-88</li>
      <li>分类列表S-89</li>
      <li>分类列表S-90</li>
      <li>分类列表S-91</li>
      <li>分类列表S-92</li>
      <li>分类列表S-93</li>
      <li>分类列表S-94</li>
      <li>分类列表S-95</li>
      <li>分类列表S-96</li>
      <li>分类列表S-97</li>
      <li>分类列表S-98</li>
      <li>分类列表S-99</li>
      <li>分类列表S-100</li>
    </ul>
  </div>
</template>

<script>
import BScroll from 'better-scroll'

export default {
  name : 'Category',
  mounted () {
    new BScroll('.wrapper',{})
  }
 }
</script>

<style scoped>
  .wrapper{
    height: 150px;
    background-color: blue;

    overflow: hidden;
    /* overflow-y: scroll; */
  }
</style>


